context:
  version: 1.0.10
package:
  name: "visitor_design_pattern"
  version: "{{ version }}"
build:
  number: 1
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed --prefix=$PREFIX .
requirements:
  build:
    - pip
    - pytest-runner
  run:
    - Click
source:
  path: .
about:
  home: https://visitor-design-pattern.readthedocs.io/en/latest/index.html

test:
  imports:
    - visitor_design_pattern
  requires:
    - pytest
  source_files:
    - tests/**/*.py
  commands:
    - pytest
